#!/bin/bash

#DATA
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_mt_17_data.conf SingleMuon_Run2017B mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_mt_17_data.conf SingleMuon_Run2017C mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_mt_17_data.conf SingleMuon_Run2017D mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_mt_17_data.conf SingleMuon_Run2017E mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_mt_17_data.conf SingleMuon_Run2017F mt 3
#Signals

./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_GluGluHToTauTau_M125_13TeV_powheg_pythia8.conf GluGluHToTauTau_M125_13TeV_powheg_pythia8 mt 5

./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_SUSYGluGluToHToTauTau_M-120_TuneCP5_13TeV-pythia8.conf SUSYGluGluToHToTauTau_M-120_TuneCP5_13TeV-pythia8 mt 5

#./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_VBFHToTauTau_M125_13TeV_powheg_pythia8.conf VBFHToTauTau_M125_13TeV_powheg_pythia8 mt 5

./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_VBF125.conf VBFHToTauTau_M125_13TeV_powheg_pythia8 mt 5


#DY

./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8.conf DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8 mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8.conf DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8 mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8.conf DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8 mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8.conf DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8 mt 3
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8.conf DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8 mt 3

#W+jets

./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8.conf WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8.conf W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8.conf W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8.conf W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8.conf W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8 mt 5

#TT

./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.conf TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8 mt 2
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_TTToSemiLeptonic_TuneCP5_PSweights_13TeV-powheg-pythia8.conf TTToSemiLeptonic_TuneCP5_PSweights_13TeV-powheg-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_TTToHadronic_TuneCP5_PSweights_13TeV-powheg-pythia8.conf TTToHadronic_TuneCP5_PSweights_13TeV-powheg-pythia8 mt 5

#VV

./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_WW_TuneCP5_13TeV-pythia8.conf WW_TuneCP5_13TeV-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_WZ_TuneCP5_13TeV-pythia8.conf WZ_TuneCP5_13TeV-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_ZZ_TuneCP5_13TeV-pythia8.conf ZZ_TuneCP5_13TeV-pythia8 mt 5

#Single Top
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_ST_t-channel_top_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8.conf ST_t-channel_top_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_ST_t-channel_antitop_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8.conf ST_t-channel_antitop_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.conf ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8 mt 5
./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.conf ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8 mt 5


#./condorsub_seq_leptau.sh SynchNTupleProducer_Run2 analysisMacroSynch_lept_mt_.conf  mt 5
